### ISSUE TITLE
zap's cool photon theme is incompatible with LibreWolf 129.0-1. 

### ISSUE THREAD

**Issue by iansquenet** [zapSNH/zapsCoolPhotonTheme#6]
### Prerequisites

- [x] I have followed the installation guide.

### Describe the Bug

![image](https://github.com/user-attachments/assets/71e2ecb4-4322-41b9-a91d-f04a5d0763cb)
Ever since the newest update, it no longer works on Librewolf.

### Expected Behavior

I expected the tabs to be stylized properly.

### OS

Windows 10

### Browser Version

Librewolf 129.0-1

**Comment by zapSNH** [comment]
Seems that you have the wrong version installed for some reason. You have `0.24.14` (the esr version which doesn't work with non-esr versions) instead of `0.24.14.1`.

A quick fix is to install the latest non-esr version of the extension here: https://github.com/zapSNH/zcpt-webextension/releases/latest.

Does LibreWolf somehow report itself as v128 while installing/updating extensions?

**Comment by iansquenet** [comment]
I'm unsure, but non-esr version worked (the esr one did work beforehand somehow tho), thank you! Though there is this line underneath the tabs now.
![image](https://github.com/user-attachments/assets/8d2f720d-a3de-4ec5-aff3-d8c521508e4e)

**Comment by zapSNH** [comment]
What theme are you using? The system auto theme or the dark theme?
